trigger:
- master


resources:
  repositories:
  - repository: azure
    type: github
    name: FasterMike/azure    
    endpoint: FasterMike

variables:
  tag: '$(Build.BuildId)'




stages:
- template: start.yml@azure


