trigger:
- master


resources:
  repositories:
  - repository: azure
    type: github
    name: FasterMike/azure
    endpoint: FasterMike


#pool:
#  vmImage: ubuntu-latest


variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'FasterMikeARC'
  imageRepository: 'fastermikeazure'
  containerRegistry: 'arcmiha.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'arcmiha1619ec65-auth'
  # Agent VM image name
#  vmImageName: 'ubuntu-16.04'


pool:
  name: Default

stages:

- template: build.yml@azure


- template: push.yml@azure


- template: deploy.yml@azure
