trigger:
- master


resources:
  repositories:
  - repository: azure
    type: github
    name: FasterMike/azure
    endpoint: FasterMike


variables:
  # Container registry service connection established during pipeline creation

  dockerRegistryServiceConnection: '07295826-36c0-4649-83c2-944d598968e3'
  imageRepository: 'fastermikeazure'
  containerRegistry: 'arcmiha.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'arcmiha1726a60d-auth'
  vmImageName: 'ubuntu-latest'

pool:
  name: Default

stages:

- template: build.yml@azure


- template: push.yml@azure


- template: deploy.yml@azure
