trigger:
- master


resources:
  repositories:
  - repository: azure
    type: github
    name: FasterMike/azure
    endpoint: FasterMike


variables:
  # Container registry service connection established during pipeline creation

  dockerRegistryServiceConnection: '61a4c511-42db-47be-9fce-94cc08b3ca36'
  imageRepository: 'fastermiketest'
  containerRegistry: 'fastermikeazure.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'fastermikeazure54068d4d-auth'

pool:
  name: Default

stages:

- template: build.yml@azure


- template: push.yml@azure


- template: deploy.yml@azure
