stages:
- stage: Push
  displayName: Push image
  jobs:  
  - job: Push
    displayName: Build
#    pool:
#      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: Push
        repository: $(imageRepository)
#        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
