stages:
- stage: Push
  displayName: Push image
  dependsOn: Build
  
  jobs:  
  - job: Push
    displayName: Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        repository: $(containerRegistry)/$(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
#          $(tag)

#    - upload: manifests
#      artifact: manifests
