stages:
- stage: Push
  displayName: Push image
  dependsOn: Build
  
  jobs:  
  - job: Push
    displayName: Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: Push
        repository: $(imageRepository)
#        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          228
    - upload: manifests
      artifact: manifests
