stages:
- stage: Push
  displayName: Push image
  dependsOn: Build
  
  jobs:  
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

#    - upload: manifests
#      artifact: manifests
