apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: fastermikeazure 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fastermikeazure 
    spec:
      containers:
        - name: fastermikeazure 
          image: arcmiha.azurecr.io/fastermikeazure
          ports:
          - containerPort: 80